[package]
name = "question_2"
version = "0.1.0"
authors = ["Sean <seli2854@colorado.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scheduler = "0.1.3"
num-traits = "0.2.8"
num-derive = "0.2.5"
